Make the required directory?
ERROR:
go: downloading github.com/techplexengineer/gontcore v0.0.0-20220517155029-254d5a24acfe
go: downloading github.com/tkrajina/go-reflector v0.5.5
Error: main.go:14:12: pattern frontend/dist: no matching files found

exit status 1

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

Error: Process completed with exit code 1.